spring:
  datasource:
    name: 't'
    username: 't'
    password: '000'
    driver-class-name: org.h2.Driver
  h2.console:
    enabled: true
    path: /h2
    settings:
      web-allow-others: true
      web-admin-password: '000'
  jpa:
    generate-ddl: true
